name: Build and Test Homies App

on:
  push:
    branches: 
      - 'develop' 
      - 'staging'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore

    - name: Run Unit Tests
      if: github.ref == 'refs/heads/develop'
      run: dotnet test --no-build --verbosity normal --filter TestCategory=Unit

    - name: Run Integration Tests
      if: github.ref == 'refs/heads/staging'
      run: dotnet test --no-build --verbosity normal --filter TestCategory=Integration
